################################# Default configuration ###################
# provide your domain here
baseURL = "https://demo.gethugothemes.com/dot/examplesite/"
# theme
theme = "dot-hugo"
# site title
title = "4flow help"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#003E52"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
name = "Facebook"
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "#"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "#"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
name = "Linkedin"
link = "#"

################################ English Language ######################
[Languages.en]
languageName = "EN"
languageCode = "en-us"
weight = 1
copyright = "Copyright &copy; 2021 a Hugo theme by [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.en.params.banner]
title = "4flow NEVA user guide"
# subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Enter your question here … "

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."

# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact/"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Releases"
url = ""
weight = 1

[[Languages.en.menu.main]]
name = "Faq"
url = "faq/"
weight = 2

[[Languages.en.menu.main]]
name = "contact"
url = "contact/"
weight = 3

# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation/"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing/"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features/"
  weight = 3


################################### German Language ######################
[Languages.de]
languageName = "DE"
languageCode = "de-de"
weight = 2
copyright = "Copyright &copy; 2021 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"

# banner
[Languages.de.params.banner]
title = "4flow NEVA Betriebsanleitung"
# subtitle = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
bg_image = "images/banner.jpg"
placeholder = "Stellen Sie Ihre Frage …"

# call to action
[Languages.de.params.cta]
enable = true
title = "Sie haben keine Antwort auf Ihre Frage gefunden?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."

# call to action button
[Languages.de.params.cta.button]
enable = true
label = "Kontakt"
link = "contact/"


################## german navigation #################
[[Languages.de.menu.main]]
name = "freigaben"
url = "/"
weight = 1

[[Languages.de.menu.main]]
name = "Faq"
url = "faq/"
weight = 2

[[Languages.de.menu.main]]
name = "kontakt"
url = "contact/"
weight = 3

# Dropdown menu
[[Languages.de.menu.main]]
weight = 4
name = "themen"
hasChildren = true

  [[Languages.de.menu.main]]
  parent = "themen"
  name = "Installation"
  url = "installation/"
  weight = 1

  [[Languages.de.menu.main]]
  parent = "themen"
  name = "Billing and Pricing"
  url = "billing-pricing/"
  weight = 2

  [[Languages.de.menu.main]]
  parent = "themen"
  name = "Features"
  url = "features/"
  weight = 3